name: GH Pages
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
      - name: sort readme # run the run.py to get the latest data
        run: |
          python sort.py
          
       - name: Commit files
         run: |
           git config --local user.email "github@uu.nl"
           git config --local user.name "GitHub Utrecht University"
           git add .
           git commit -m "sort README"
        continue-on-error: true
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
          
